name: build
on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        AGP:
          - 4.2.2
          - 7.0.0
          - 7.0.1
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 11

      - run: perl -pe 's/AGP_VERSION_PLACEHOLDER/${{ matrix.AGP }}/' -i build.gradle
      - run: cat build.gradle

      - run: ./gradlew build

      - run: unzip -v app/build/outputs/apk/release/app-release-unsigned.apk

      - run: unzip -v app/build/outputs/apk/release/app-release-unsigned.apk | grep lib

      - run: unzip -v app/build/outputs/apk/release/app-release-unsigned.apk | grep lib -q
